=== DDTH/dPHP/src/package.dtd
<!-- $Id$ -->

<!ELEMENT package (name, version, description, summary, author, dependencies)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT version (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT summary (#PCDATA)>

<!ELEMENT author (author-name, author-email)>
<!ELEMENT author-name (#PCDATA)>
<!ELEMENT author-email (#PCDATA)>

<!ELEMENT dependencies (dependency*)>

<!ELEMENT dependency (dependency-name, dependency-version-min?, dependency-version-max?, dependency-description?)>
<!ELEMENT dependency-name (#PCDATA)>
<!ELEMENT dependency-version-min (#PCDATA)>
<!ELEMENT dependency-version-max (#PCDATA)>
<!ELEMENT dependency-description (#PCDATA)>

=== DDTH/dPHP/src/Duser/php5/Ddth/Duser/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE package PUBLIC
	"-//dPHP Package Description DTD//EN"
	"https://raw.github.com/DDTH/dPHP/master/src/package.dtd">
<package>
	<name>Ddth::Duser</name>
	<version>0.1</version>
	<description>User management library.</description>
	<summary>
		This library provides a simple API for user-management. The
		API provides the access to the following functions:
		- Credentials
		-
		Access Control
		- Profile Management
	</summary>
	<author>
		<author-name>Thanh Ba Nguyen</author-name>
		<author-email>
			btnguyen2k@gmail.com
		</author-email>
	</author>
	<dependencies>
		<dependency>
			<dependency-name>PHP</dependency-name>
			<dependency-version-min>5.0</dependency-version-min>
			<dependency-description></dependency-description>
		</dependency>
		<dependency>
			<dependency-name>Ddth::Commons</dependency-name>
			<dependency-version-min>0.1</dependency-version-min>
			<dependency-description>
			</dependency-description>
		</dependency>
	</dependencies>
</package>

=== DDTH/dPHP/src/Vivn/php5/Ddth/Vivn/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE package PUBLIC
	"-//dPHP Package Description DTD//EN"
	"https://raw.github.com/DDTH/dPHP/master/src/package.dtd">
<package>
	<name>Ddth::Vnvi</name>
	<version>0.1</version>
	<description>Library to support vi_VN locale.</description>
	<summary>
		This library aims to provide support for vi_VN locale in PHP.
	</summary>
	<author>
		<author-name>Thanh Ba Nguyen</author-name>
		<author-email>
			btnguyen2k@gmail.com
		</author-email>
	</author>
	<dependencies>
		<dependency>
			<dependency-name>PHP</dependency-name>
			<dependency-version-min>5.0</dependency-version-min>
			<dependency-description></dependency-description>
		</dependency>
		<dependency>
			<dependency-name>PHP-mbstring</dependency-name>
			<dependency-description>
				PHP must be compiled with --enable-mbstring.
			</dependency-description>
		</dependency>
	</dependencies>
</package>
